name: sponsorbabeinfogawat
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  three_js: ^0.1.7
  file_picker: ^8.1.0
  ffmpeg_kit_flutter_new_audio: ^1.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  share_plus: ^10.0.3
  audio_waveforms: ^1.1.0
  device_info_plus: ^9.1.1
flutter:
  assets:
    - assets/images/babe_gold.jpg
    - assets/images/bg.jpg
    - web/babe.html