name: babe_info_fixed
description: BABE.INFO - Globe Fixed Learn three_js
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  file_picker: ^8.1.0
  ffmpeg_kit_flutter_new_audio: ^1.0.0
  path_provider: ^2.1.2
  share_plus: ^10.0.3
flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
    - assets/images/babe_gold.jpg
    - web/babe.html