name: sponsorbabeinfogawat
description: Sponsor Babe Info Gawat
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  three_js: 0.1.7
  three_js_controls: 0.1.0
  flutter_angle: 0.2.8
  path_provider: 2.1.5
  permission_handler: 11.4.0
  share_plus: 10.1.4
  device_info_plus: 9.1.2
  file_picker: ^10.3.2
  just_audio: ^0.10.4
  audio_waveforms: ^2.0.2
  flutter_screen_recording: ^2.0.25
  sherpa_onnx: ^1.10.20
  http: ^1.2.0
  ffmpeg_kit_flutter_new: ^4.6.2
  #mp3: ^1.0.0
  #wav: ^1.1.0

dependency_overrides:
  uuid: ^4.4.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/globe.frag

  assets:
    - assets/
    - assets/images/bg.jpg
    - assets/images/babe_info.png